name: go_tour
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
#  sdk: '>=2.12.0 <3.0.0'
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
#  get: ^4.6.1
  dots_indicator: ^2.1.0
  flutter_screenutil: ^5.3.1
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.15
  #flutter_rating_bar: ^4.0.0
  dotted_border: ^2.0.0+2
  flutter_credit_card: ^3.0.1
  flutter_map: ^0.14.0
  latlong2: ^0.8.1
  http: ^0.13.4
  get: ^4.6.1
  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  path_provider: ^2.0.11
#  get_storage: ^2.0.3
  flutter:
    sdk: flutter
  
  card_swiper: ^2.0.1
  flutter_rating_bar: ^4.0.0 
  intl_phone_field: ^3.0.1
  # flutter_custom_clippers: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^2.3.1
  # device_preview: ^0.7.4
  # dotted_border: ^2.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    #- assets/fonts/

